#!/bin/bash
# GoldenDog Linux Patch Service
# Author: Alexia Michelle <alexia@goldendoglinux.org>
# To disable automatic patching, in your goldendog installation do:
# sudo systemctl disable patch-service.service (NOT RECOMMENDED)
# Alternatively, you can change the variable from "true" to "false" in /usr/local/bin/patch-service
logdate=$(date +%Y-%m-%d)
###################################################################################################
#!/bin/bash
if [ "$(whoami)" != "$(logname)" ]; then
echo "This fix must be ran as user $(logname)"
echo "Aborting"
exit 1
else
cd
mkdir -p Downloads && mkdir -p Documents && mkdir -p Games && mkdir -p Music && mkdir -p Pictures && mkdir -p Videos
echo "Created the following dirs:"
ls -d */
echo "Fix applied [ OK ]"
fi

current_user=$(logname)
file_path="$HOME/.local/share/user-places.xbel"
if [[ -f "$file_path" ]]; then
    sed -i "s/pupper/$current_user/g" "$file_path"
    cp "$file_path" "$file_path.bak"
    echo "Replaced 'pupper' with '$current_user' in $file_path. [ OK ]"


content='XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"'

echo "$content" > ~/.config/user-dirs.dirs

# Optional: Print a message indicating success
echo "Updated ~/.config/user-dirs.dirs with the specified directories. [ OK ]"


else
    echo "File $file_path does not exist."
fi

# Commented just now. Only useful for scripts that require sudo.
echo "Plasma needs to be rehashed for changes to take effect. Proceed? [Y/N]"
read x

case $x in
YySs)
kquitapp5 plasmashell && kstart5 plasmashell
;;
Nn)
echo "Aborted"
exit 1
;;
*)
exit 1
;;
echo -e "${logdate} System integrity [ OK ]\nNo patches applied." > /var/log/goldendog-security.log
esac
