#!/bin/bash
# GoldenDog Linux Patch Service
# Author: Alexia Michelle <alexia@goldendoglinux.org>
# To disable automatic patching, in your goldendog installation do:
# sudo systemctl disable patch-service.service (NOT RECOMMENDED)
# Alternatively, you can change the variable from "true" to "false" in /usr/local/bin/patch-service
logdate=$(date +%Y-%m-%d)
green=$(tput setaf 2)
reset=$(tput sgr0)
ok="${green}[${reset} OK ${green}]${reset}"
###################################################################################################
clear
if [ "$(whoami)" != "$(logname)" ]; then
echo "This fix must be ran as user $(logname)"
echo "Aborting"
exit 1
else
echo "This patch was for 1.6.14. It is now obsolete. There's nothing to patch. Update to 1.6.19"
fi
