#!/bin/bash
# GoldenDog Linux Patch Service
# Author: Alexia Michelle <alexia@goldendoglinux.org>
# To disable automatic patching, in your goldendog installation do:
# sudo systemctl disable patch-service.service (NOT RECOMMENDED)
# Alternatively, you can change the variable from "true" to "false" in /usr/local/bin/patch-service
logdate=$(date +%Y-%m-%d)
green=$(tput setaf 2)
reset=$(tput sgr0)
ok="${green}[${reset} OK ${green}]${reset}"
###################################################################################################
clear
cp patch-service /usr/local/bin; chmod +x /usr/local/bin/patch-service
echo "$(date) - Fixed URL for the GIT service server" > /var/log/goldendog-patch.log
